Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -72,7 +72,10 @@ jobs:
           echo "Listing JaCoCo reports..."
           ls -R target/site || echo "❌ target/site missing"
           find target -name jacoco.xml || echo "❌ jacoco.xml not found!"
-
+      - name: List JaCoCo output files
+        run: |
+          echo "Listing JaCoCo reports..."
+          ls -R ./target/site/jacoco || echo "❌ jacoco.xml not found!"  
       - name: Upload Backend Coverage to Codecov
         uses: codecov/codecov-action@v5
         with:
@@ -94,10 +97,6 @@ jobs:
         uses: actions/checkout@v4
       - name: Validate Codecov YAML
         run: curl --data-binary @.codecov.yml https://codecov.io/validate  
-      - name: List JaCoCo output files
-        run: |
-          echo "Listing JaCoCo reports..."
-          ls -R backend/target/site/jacoco || echo "❌ jacoco.xml not found!"  
       - name: Post Coverage Comment
         uses: codecov/codecov-action@v5
         with:
